require 'jsonapi-ruby-deserializer/resource'
require 'jsonapi-ruby-deserializer/document'
require 'jsonapi-ruby-deserializer/links'
require 'jsonapi-ruby-deserializer/meta'
require 'jsonapi-ruby-deserializer/errors'
require 'jsonapi-ruby-deserializer/jsonapi'
require 'jsonapi-ruby-deserializer/attributes'
require 'jsonapi-ruby-deserializer/relationships'
